### ISSUE TITLE
Skeletons - Lights

### ISSUE THREAD

**Issue by DzInLa** [NMC-TBone/I3D-Exporter-Additionals#7]
Hi T-Bone,

When I create Lights with the Skeletons function the Turn Lights Front and Back both face forward direction at different angles .

Also with the lights, will a future update have the lights settings as per your tutorial?
Or are the settings already set for the Giants Editor.

I was using Blender 3.2.1 with only a plane mesh created when using your awesome addon. 

David

**Comment by NMC-TBone** [comment]
Hello 😄 

Will take a look at the ligghts in skeletons, thanks for letting me know 😉 

The lights should get the correct settings set for Giants Editor when you create the skeleton, but of course there could be issues.
